# Generated by Django 6.0.5 on 2026-05-08 04:01

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название категории')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('is_regular', models.BooleanField(default=False, verbose_name='Регулярный расход')),
            ],
            options={
                'verbose_name': 'Категория расхода',
                'verbose_name_plural': 'Категории расходов',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=100, verbose_name='Марка')),
                ('model', models.CharField(max_length=100, verbose_name='Модель')),
                ('year', models.PositiveIntegerField(verbose_name='Год выпуска')),
                ('fuel_type', models.CharField(choices=[('petrol', 'Бензин'), ('diesel', 'Дизель'), ('gas', 'Газ'), ('hybrid', 'Гибрид'), ('electric', 'Электро')], max_length=20, verbose_name='Тип топлива')),
                ('engine_volume', models.DecimalField(decimal_places=1, max_digits=3, verbose_name='Объем двигателя')),
                ('mileage', models.PositiveIntegerField(default=0, verbose_name='Пробег')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cars', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Автомобиль',
                'verbose_name_plural': 'Автомобили',
                'ordering': ['brand', 'model'],
            },
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сумма')),
                ('expense_date', models.DateField(default=django.utils.timezone.now, verbose_name='Дата расхода')),
                ('mileage', models.PositiveIntegerField(blank=True, null=True, verbose_name='Пробег на момент расхода')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='cars.car', verbose_name='Автомобиль')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expenses', to='cars.expensecategory', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Расход',
                'verbose_name_plural': 'Расходы',
                'ordering': ['-expense_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MonthlyForecast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forecast_month', models.DateField(verbose_name='Месяц прогноза')),
                ('predicted_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Прогнозируемая сумма')),
                ('calculation_description', models.TextField(verbose_name='Описание расчета')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания прогноза')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forecasts', to='cars.car', verbose_name='Автомобиль')),
            ],
            options={
                'verbose_name': 'Прогноз расходов',
                'verbose_name_plural': 'Прогнозы расходов',
                'ordering': ['-forecast_month'],
            },
        ),
    ]
